# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
import_types = ["diesel::sql_types::*"]
# Exclude TimescaleDB internal tables
filter = { except_tables = ["_timescaledb_internal.*", "_timescaledb_catalog.*", "_timescaledb_config.*"] }


[migrations_directory]
dir = "migrations"

