style_edition = "2024"
omment_width = 100
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
imports_layout = "Vertical"
imports_granularity = "Crate"
newline_style = "Unix"
tab_spaces = 2
wrap_comments = true
use_small_heuristics = "Max"
