#  Commented items are for nighly versions of rust
style_edition = "2024"
#comment_width = 80
#group_imports = "StdExternalCrate"
#format_code_in_doc_comments = true
#imports_layout = "Vertical"
#imports_granularity = "Crate"
newline_style = "Unix"
tab_spaces = 2
#wrap_comments = true
use_small_heuristics = "Max"
