/*
 *
 *
 *
 *
 * MIT License
 * Copyright (c) 2025. Dwight J. Browne
 * dwight[-at-]dwightjbrowne[-dot-]com
 *
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//! Missing symbol resolver for `av-cli load missing-symbols`.
//!
//! This module is the **resolution pass** for symbols logged by
//! [`super::missing_symbol_logger`]. When the news, ticker-sentiment, or
//! top-movers loaders encounter symbols that don't exist in the local
//! `symbols` table, they record them in `missing_symbols` with
//! `resolution_status = "pending"`. This command reads those pending entries
//! and attempts to resolve each one via the AlphaVantage `SYMBOL_SEARCH`
//! endpoint.
//!
//! ## Resolution Outcomes
//!
//! Each pending symbol ends up in one of four states:
//!
//! - **Found** ([`ResolutionResult::Found`]) — Symbol search returned a match,
//!   a new row was inserted into `symbols` (with a fresh SID generated by
//!   [`SidGenerator`]), and the `missing_symbols` row is marked as found.
//!   Optionally fetches a company overview (best-effort).
//! - **Not found** ([`ResolutionResult::NotFound`]) — Symbol search returned
//!   no matches; the `missing_symbols` row is marked as not-found.
//! - **Skipped** ([`ResolutionResult::Skipped`]) — The symbol was a non-equity
//!   prefix (e.g., `CRYPTO:`, `FOREX:`, `INDEX:`, `COMMODITY:`), or AlphaVantage
//!   returned an unknown `stock_type`, or `--auto-skip` was set and a search
//!   error occurred. The `missing_symbols` row is marked as skipped.
//! - **Error** — A retriable failure (rate limit, API key error, or
//!   non-skipped search error). Returns an error from
//!   [`fetch_and_store_overview`]; aborts the run unless `--continue-on-error`
//!   is set.
//!
//! ## Pipeline
//!
//! ```text
//! missing_symbols (resolution_status = "pending")
//!   │
//!   ▼  ordered by seen_count DESC, optionally filtered by --source / --limit
//! for each pending symbol:
//!   │
//!   ▼
//! normalize_symbol_for_query()  ── strips prefixes, classifies SecurityType
//!   │
//!   ├── non-Equity → mark_skipped (not supported)
//!   │
//!   ▼  Equity
//! AlphaVantageClient.symbol_search()
//!   │
//!   ├── error → propagate (or skip if --auto-skip)
//!   ├── empty → mark_not_found
//!   │
//!   ▼  best-match (highest match_score)
//! check existing symbols(symbol, sec_type)
//!   │
//!   ├── exists → reuse SID
//!   │
//!   ▼  not exists
//! INSERT INTO symbols (sid from SidGenerator, region/currency normalized)
//!   │
//!   ▼
//! mark_found (in missing_symbols)
//!   │
//!   ▼
//! [optional] fetch company_overview → set symbols.overview = true
//! ```
//!
//! ## Best-Match Selection
//!
//! When AlphaVantage returns multiple matches, the one with the highest
//! `match_score` is selected. Match scores are floats in the range `[0.0, 1.0]`
//! returned as strings by the API.
//!
//! ## Region/Currency Normalization
//!
//! AlphaVantage returns full region names (e.g., `"United States"`) and
//! sometimes long currency codes. These are normalized:
//!
//! - **Region** — Via [`super::securities::normalize_alpha_region`] to fit
//!   the `varchar(10)` `symbols.region` column.
//! - **Currency** — Truncated to 10 characters if longer.
//!
//! ## Usage
//!
//! ```bash
//! # Resolve all pending missing symbols
//! av-cli load missing-symbols
//!
//! # Resolve only news_feed symbols, max 50, auto-skip on errors
//! av-cli load missing-symbols --source news_feed --limit 50 --auto-skip
//!
//! # Dry run to preview what would be processed
//! av-cli load missing-symbols --dry-run
//!
//! # Strict mode (abort on first error)
//! av-cli load missing-symbols --no-continue-on-error
//! ```

use anyhow::{Result, anyhow};
use clap::Args;
use diesel::prelude::*;
use indicatif::{ProgressBar, ProgressStyle};
use std::time::Duration;
use tokio::time::sleep;
use tracing::{debug, error, info, warn};

use super::securities::normalize_alpha_region;
use super::sid_generator::SidGenerator;
use crate::config::Config;
use av_client::AlphaVantageClient;
use av_core::types::market::SecurityType;
use av_database_postgres::models::{MissingSymbol, NewSymbolOwned};
use av_database_postgres::schema::{missing_symbols, symbols};

/// Sentinel priority value for symbols loaded via the missing-symbol resolver.
///
/// New symbols are inserted with this priority because they originate from
/// "found via news feed" rather than from a curated bulk load — they're
/// non-primary by definition and should not appear in primary-only loaders
/// like [`super::crypto_intraday`].
//todo: Need to refactor
const NO_PRIORITY: i32 = 9_999_999;

/// Command-line arguments for `av-cli load missing-symbols`.
///
/// Controls source filtering, batch size, rate limiting, and error/skip behavior.
#[derive(Args, Debug)]
pub struct MissingSymbolsArgs {
  /// Filter pending symbols by source field (e.g., `news_feed`,
  /// `ticker_sentiment`, `top_movers`).
  ///
  /// When omitted, processes pending symbols from all sources.
  #[arg(long)]
  source: Option<String>,

  /// Cap the number of symbols to process in this run.
  ///
  /// Useful for managing API rate limits or splitting work across multiple
  /// invocations.
  #[arg(short, long)]
  limit: Option<usize>,

  /// Delay between AlphaVantage API requests in milliseconds.
  ///
  /// Defaults to 800 ms ≈ 75 calls/minute, suitable for the AlphaVantage
  /// premium tier.
  #[arg(long, default_value = "800")]
  delay_ms: u64,

  /// Continue processing remaining symbols on error. Defaults to `true`.
  ///
  /// Use `--no-continue-on-error` to abort on the first error (rate limits
  /// and API key failures always abort regardless).
  #[arg(short = 'k', long, default_value = "true")]
  continue_on_error: bool,

  /// Preview mode — log what would be processed without API calls or DB writes.
  #[arg(short, long)]
  dry_run: bool,

  /// On non-fatal search errors, mark the symbol as `skipped` instead of
  /// returning an error.
  ///
  /// When `false` (default), unknown errors propagate. When `true`, the
  /// symbol is recorded with the error message in `resolution_details` and
  /// processing continues with the next symbol.
  #[arg(long)]
  auto_skip: bool,
}

/// Main entry point for `av-cli load missing-symbols`.
///
/// Orchestrates the resolution pipeline:
///
/// 1. **Query pending symbols** — Reads `missing_symbols` rows where
///    `resolution_status = "pending"`, ordered by `seen_count DESC` (most-seen
///    first), optionally filtered by `--source` and capped by `--limit`.
/// 2. **Dry-run check** — If `--dry-run`, logs the would-be-processed symbols
///    and returns.
/// 3. **Setup** — Creates [`AlphaVantageClient`] and initializes a
///    [`SidGenerator`] from the database.
/// 4. **Per-symbol resolution** — For each pending symbol:
///    - Sleeps `delay_ms` for rate limiting
///    - Calls [`fetch_and_store_overview`]
///    - Tracks counts: found, not_found, skipped, errors
///    - Aborts on error unless `--continue-on-error`
/// 5. **Final report** — Prints the four counters with emoji indicators.
///
/// # Errors
///
/// Returns errors from: pending query, SID generator init, or any resolution
/// error when `--continue-on-error = false`.
pub async fn execute(args: MissingSymbolsArgs, config: Config) -> Result<()> {
  info!("Starting missing symbol resolver");

  // Get pending missing symbols
  let pending_symbols = tokio::task::spawn_blocking({
    let database_url = config.database_url.clone();
    let source_filter = args.source.clone();
    let limit = args.limit;

    move || -> Result<Vec<MissingSymbol>> {
      let mut conn = diesel::PgConnection::establish(&database_url)?;

      let mut query = missing_symbols::table
        .filter(missing_symbols::resolution_status.eq("pending"))
        .order_by(missing_symbols::seen_count.desc())
        .into_boxed();

      if let Some(source) = source_filter {
        query = query.filter(missing_symbols::source.eq(source));
      }

      if let Some(lim) = limit {
        query = query.limit(lim as i64);
      }

      let results = query.load::<MissingSymbol>(&mut conn)?;
      Ok(results)
    }
  })
  .await??;

  if pending_symbols.is_empty() {
    info!("No pending missing symbols to process");
    return Ok(());
  }

  info!("Found {} pending symbols to resolve", pending_symbols.len());

  if args.dry_run {
    info!("Dry run mode - no API calls or database updates");
    for symbol in &pending_symbols {
      info!(
        "Would process: {} (source: {}, seen {} times)",
        symbol.symbol, symbol.source, symbol.seen_count
      );
    }
    return Ok(());
  }

  // Create API client
  let client = AlphaVantageClient::new(config.api_config.clone())
    .map_err(|e| anyhow!("Failed to create API client: {}", e))?;

  // Initialize SID generator
  let mut sid_generator = tokio::task::spawn_blocking({
    let database_url = config.database_url.clone();
    move || -> Result<SidGenerator> {
      let mut conn = diesel::PgConnection::establish(&database_url)?; //todo: decouple from Postgres
      SidGenerator::new(&mut conn)
    }
  })
  .await??;

  let progress = ProgressBar::new(pending_symbols.len() as u64);
  progress.set_style(
    ProgressStyle::default_bar()
      .template("[{elapsed_precise}] {bar:40.cyan/blue} {pos:>7}/{len:7} {msg}")
      .expect("Invalid progress bar template")
      .progress_chars("##-"),
  );

  let mut found_count = 0;
  let mut not_found_count = 0;
  let mut skipped_count = 0;
  let mut error_count = 0;

  for missing_symbol in pending_symbols {
    progress.set_message(format!("Processing {}", missing_symbol.symbol));

    // Apply rate limiting
    sleep(Duration::from_millis(args.delay_ms)).await;

    // Try to fetch overview from AlphaVantage
    let result = fetch_and_store_overview(
      &client,
      &config.database_url,
      &missing_symbol,
      args.auto_skip,
      &mut sid_generator,
    )
    .await;

    match result {
      Ok(ResolutionResult::Found(sid)) => {
        found_count += 1;
        info!("✓ Found and loaded: {} (SID: {})", missing_symbol.symbol, sid);
      }
      Ok(ResolutionResult::NotFound(reason)) => {
        not_found_count += 1;
        warn!("✗ Not found: {} - {}", missing_symbol.symbol, reason);
      }
      Ok(ResolutionResult::Skipped(reason)) => {
        skipped_count += 1;
        info!("⊘ Skipped: {} - {}", missing_symbol.symbol, reason);
      }
      Err(e) => {
        error_count += 1;
        error!("Error processing {}: {}", missing_symbol.symbol, e);

        if !args.continue_on_error {
          progress.finish_with_message("Stopped due to error");
          return Err(e);
        }
      }
    }

    progress.inc(1);
  }

  progress.finish_with_message("Symbol resolution complete");

  info!("📊 Resolution statistics:");
  info!("  - Found and loaded: {}", found_count);
  info!("  - Not found: {}", not_found_count);
  info!("  - Skipped: {}", skipped_count);
  info!("  - Errors: {}", error_count);

  Ok(())
}

/// Outcome of resolving a single missing symbol.
///
/// Returned by [`fetch_and_store_overview`] and matched on by [`execute`] to
/// update statistics. Each variant carries either the resolved SID or a
/// human-readable reason string for logging.
enum ResolutionResult {
  /// Symbol was successfully resolved and inserted (or matched an existing row).
  /// Carries the SID of the resolved symbol.
  Found(i64),
  /// AlphaVantage returned no matches for the symbol. Carries the reason.
  NotFound(String),
  /// Symbol was deliberately skipped (unsupported type, unknown stock_type,
  /// or `--auto-skip` triggered on a search error). Carries the reason.
  Skipped(String),
}

/// Normalizes a missing symbol string and infers its [`SecurityType`].
///
/// Handles prefixed symbols from news feeds (e.g., `CRYPTO:BTC`, `FOREX:EUR`,
/// `INDEX:SPX`, `COMMODITY:GOLD`) by stripping the prefix and returning the
/// appropriate type. Unprefixed symbols are treated as [`SecurityType::Equity`].
///
/// Returns `(normalized_symbol, security_type)`. Only Equity symbols are
/// resolvable by this loader; non-Equity types are flagged for skipping by
/// the caller.
fn normalize_symbol_for_query(symbol: &str) -> (String, SecurityType) {
  // Handle prefixed symbols from news feeds
  if let Some(stripped) = symbol.strip_prefix("CRYPTO:") {
    return (stripped.to_string(), SecurityType::Cryptocurrency);
  }

  // Skip FOREX, INDEX, COMMODITY - these aren't equities/ETFs/mutual funds
  if symbol.starts_with("FOREX:") {
    return (symbol.to_string(), SecurityType::Currency);
  }
  if symbol.starts_with("INDEX:") {
    return (symbol.to_string(), SecurityType::Index);
  }
  if symbol.starts_with("COMMODITY:") {
    return (symbol.to_string(), SecurityType::Commodity);
  }

  (symbol.to_string(), SecurityType::Equity)
}

/// Resolves a single missing symbol via AlphaVantage and persists the result.
///
/// This is the per-symbol orchestration function called by [`execute`] for
/// each pending row. The 5-step pipeline:
///
/// 1. **Normalize and classify** — Calls [`normalize_symbol_for_query`].
///    Non-Equity symbols (Crypto, Forex, Index, Commodity) are immediately
///    marked as skipped via [`MissingSymbol::mark_skipped`] and the function
///    returns [`ResolutionResult::Skipped`].
/// 2. **Symbol search** — Calls `AlphaVantageClient.symbol_search()`.
///    - Empty `best_matches` → [`MissingSymbol::mark_not_found`] → returns
///      [`ResolutionResult::NotFound`].
///    - Rate limit / API key error → propagates as `Err` (always retriable).
///    - Other errors → propagated, or skipped if `auto_skip = true`.
///    - Otherwise → picks the match with the highest `match_score` (parsed
///      as `f64`).
/// 3. **Type validation** — Maps `stock_type` to [`SecurityType`] via
///    [`SecurityType::from_alpha_vantage`]. If `Other` (unknown), marks as
///    skipped and returns.
/// 4. **Symbol insertion** — Inside `spawn_blocking`:
///    - Checks if `(symbol, sec_type)` already exists; reuses the SID if so.
///    - Otherwise generates a new SID via `sid_generator.next_sid(security_type)`
///      and inserts a [`NewSymbolOwned`] with `priority = NO_PRIORITY`,
///      normalized region (via [`super::securities::normalize_alpha_region`]),
///      and truncated currency. `overview = false` initially.
/// 5. **Mark found and fetch overview** —
///    - [`MissingSymbol::mark_found`] records the resolution with the new SID
///      and a descriptive details string.
///    - Best-effort `company_overview` call: on success, sets
///      `symbols.overview = true`. Failures are logged at debug level and
///      don't affect the resolution outcome.
///
/// Returns the appropriate [`ResolutionResult`] variant.
async fn fetch_and_store_overview(
  client: &AlphaVantageClient,
  database_url: &str,
  missing_symbol: &MissingSymbol,
  auto_skip: bool,
  sid_generator: &mut SidGenerator,
) -> Result<ResolutionResult> {
  let symbol = &missing_symbol.symbol;

  // Normalize the symbol for API query
  let (query_symbol, sec_type) = normalize_symbol_for_query(symbol);

  if sec_type != SecurityType::Equity {
    let reason = format!("unsupported: {}", sec_type);
    tokio::task::spawn_blocking({
      let database_url = database_url.to_string();
      let id = missing_symbol.id;
      let details = Some(reason.clone());

      move || -> Result<()> {
        let mut conn = diesel::PgConnection::establish(&database_url)?;
        MissingSymbol::mark_skipped(&mut conn, id, details)?;
        Ok(())
      }
    })
    .await??;

    return Ok(ResolutionResult::Skipped(reason));
  }

  // Step 1: Search for the symbol using SYMBOL_SEARCH endpoint
  debug!("Searching for symbol: {} (query: {})", symbol, query_symbol);

  let search_result = client.time_series().symbol_search(&query_symbol).await;

  let found_symbol = match search_result {
    Ok(search_response) => {
      if search_response.best_matches.is_empty() {
        // No matches found in symbol search
        tokio::task::spawn_blocking({
          let database_url = database_url.to_string();
          let id = missing_symbol.id;
          let details = Some("No matches found in symbol search".to_string());

          move || -> Result<()> {
            let mut conn = diesel::PgConnection::establish(&database_url)?;
            MissingSymbol::mark_not_found(&mut conn, id, details)?;
            Ok(())
          }
        })
        .await??;

        return Ok(ResolutionResult::NotFound("No matches in symbol search".to_string()));
      }

      // Step 2: Select the best match (first one with highest match score)
      let best_match = search_response
        .best_matches
        .iter()
        .max_by(|a, b| {
          let score_a = a.match_score.parse::<f64>().unwrap_or(0.0);
          let score_b = b.match_score.parse::<f64>().unwrap_or(0.0);
          score_a.partial_cmp(&score_b).unwrap_or(std::cmp::Ordering::Equal)
        })
        .unwrap(); // Safe because we checked is_empty above

      info!(
        "Found match: {} ({}) - Type: {}, Score: {}",
        best_match.symbol, best_match.name, best_match.stock_type, best_match.match_score
      );

      best_match.clone()
    }
    Err(e) => {
      // Handle search API errors
      let error_msg = e.to_string();

      if error_msg.contains("rate limit") || error_msg.contains("429") {
        return Err(anyhow::anyhow!("Rate limit exceeded"));
      }

      if error_msg.contains("Invalid API") {
        return Err(anyhow::anyhow!("API key invalid or missing"));
      }

      // Unknown error
      if auto_skip {
        tokio::task::spawn_blocking({
          let database_url = database_url.to_string();
          let id = missing_symbol.id;
          let reason = Some(format!("Search API error: {}", error_msg));

          move || -> Result<()> {
            let mut conn = diesel::PgConnection::establish(&database_url)?;
            MissingSymbol::mark_skipped(&mut conn, id, reason)?;
            Ok(())
          }
        })
        .await??;

        return Ok(ResolutionResult::Skipped(format!("Search API error: {}", error_msg)));
      } else {
        return Err(e.into());
      }
    }
  };

  // Step 3: Determine security type from search result
  let security_type = SecurityType::from_alpha_vantage(&found_symbol.stock_type);

  // Skip "Other" types as we don't know how to handle them
  if security_type == SecurityType::Other {
    tokio::task::spawn_blocking({
      let database_url = database_url.to_string();
      let id = missing_symbol.id;
      let stock_type = found_symbol.stock_type.clone();
      let details = Some(format!("Skipped: Unknown stock_type '{}'", stock_type));

      move || -> Result<()> {
        let mut conn = diesel::PgConnection::establish(&database_url)?;
        MissingSymbol::mark_skipped(&mut conn, id, details)?;
        Ok(())
      }
    })
    .await??;

    return Ok(ResolutionResult::Skipped(format!(
      "Unknown stock_type: '{}'",
      found_symbol.stock_type
    )));
  }

  // Step 4: Check if symbol already exists (by symbol AND sec_type)
  let sid = tokio::task::spawn_blocking({
    let database_url = database_url.to_string();
    let symbol_str = found_symbol.symbol.clone();
    let name = found_symbol.name.clone();
    let region_raw = found_symbol.region.clone();
    let currency_raw = found_symbol.currency.clone();
    let sec_type_str = format!("{:?}", security_type);
    let new_sid = sid_generator.next_sid(security_type);

    move || -> Result<i64> {
      let mut conn = diesel::PgConnection::establish(&database_url)?;

      // Check if symbol already exists with this sec_type (composite uniqueness)
      let existing_sid: Option<i64> = symbols::table
        .filter(symbols::symbol.eq(&symbol_str))
        .filter(symbols::sec_type.eq(&sec_type_str))
        .select(symbols::sid)
        .first(&mut conn)
        .optional()?;

      if let Some(sid) = existing_sid {
        info!(
          "Symbol {} already exists with sec_type {} and SID: {}",
          symbol_str, sec_type_str, sid
        );
        return Ok(sid);
      }

      // Normalize region and currency to fit database constraints (varchar(10))
      let region = normalize_alpha_region(&region_raw);
      let currency =
        if currency_raw.len() > 10 { currency_raw[..10].to_string() } else { currency_raw };

      // Insert new symbol
      let new_symbol = NewSymbolOwned {
        sid: new_sid,
        symbol: symbol_str.clone(),
        priority: NO_PRIORITY,
        name: name.clone(),
        sec_type: sec_type_str.clone(),
        region: region.clone(),
        currency: currency.clone(),
        overview: false, // Will be set to true after fetching overview
        intraday: false,
        summary: false,
        c_time: chrono::Utc::now().naive_utc(),
        m_time: chrono::Utc::now().naive_utc(),
      };

      diesel::insert_into(symbols::table).values(&new_symbol).execute(&mut conn)?;

      info!(
        "Inserted new symbol: {} with SID: {} (sec_type: {}, region: {})",
        symbol_str, new_sid, sec_type_str, region
      );
      Ok(new_sid)
    }
  })
  .await??;

  // Mark as found in missing_symbols table (found via symbol search)
  tokio::task::spawn_blocking({
    let database_url = database_url.to_string();
    let id = missing_symbol.id;
    let symbol_info = format!("{} ({})", found_symbol.name, found_symbol.stock_type);
    let details = Some(format!("Resolved via symbol search as {}", symbol_info));

    move || -> Result<()> {
      let mut conn = diesel::PgConnection::establish(&database_url)?;
      MissingSymbol::mark_found(&mut conn, id, sid, details)?;
      Ok(())
    }
  })
  .await??;

  // Step 5: Try to fetch overview (best effort - optional additional data)
  debug!("Fetching overview for found symbol: {}", found_symbol.symbol);

  match client.fundamentals().company_overview(&found_symbol.symbol).await {
    Ok(overview) => {
      if !overview.symbol.is_empty() {
        // Update the symbol record to mark overview=true
        tokio::task::spawn_blocking({
          let database_url = database_url.to_string();
          let symbol_sid = sid;

          move || -> Result<()> {
            let mut conn = diesel::PgConnection::establish(&database_url)?;

            diesel::update(symbols::table.filter(symbols::sid.eq(symbol_sid)))
              .set(symbols::overview.eq(true))
              .execute(&mut conn)?;

            Ok(())
          }
        })
        .await??;

        info!(
          "Successfully fetched and stored overview for {} (SID: {})",
          found_symbol.symbol, sid
        );
      } else {
        debug!("Overview returned empty for {} - skipping", found_symbol.symbol);
      }
    }
    Err(e) => {
      // Overview fetch failed, but symbol is already found and in the table
      debug!(
        "Failed to fetch overview for {} (SID: {}): {} - continuing",
        found_symbol.symbol, sid, e
      );
    }
  }

  Ok(ResolutionResult::Found(sid))
}
